hmcts/chart-ccd

Makefile
azure-pipelines.yml
ccd/Chart.yaml
ccd/templates/api-gateway-service.yaml
ccd/templates/api-gateway.yaml
ccd/templates/case-management-web-service.yaml
ccd/templates/case-management-web.yaml
ccd/templates/data-store-api-service.yaml
ccd/templates/data-store-api.yaml
ccd/templates/definition-store-api-service.yaml
ccd/templates/definition-store-api.yaml
ccd/templates/ingress.yaml
ccd/templates/user-profile-api-service.yaml
ccd/templates/user-profile-api.yaml
ccd/values.yaml
ci-values.yaml

https://tools.hmcts.net/jira/browse/RPE-871
Added all mandatory services for CCD
There is more optional services that can be included by a team that requires them /  in follow up PRs
TODOs have been left in some places for follow up PRs that are left
Main things outstanding on this story not covered in this PR:
few things left to do on my story:
* test by including with another application chart, rhubarb should be good enough for my needs
```
[ ] Yes
[ ] No
```

RPE-871 All services included

---

ccd/templates/api-gateway-service.yaml
ccd/templates/api-gateway.yaml
ccd/templates/case-management-web-service.yaml
ccd/templates/case-management-web.yaml
ccd/templates/dns.yaml
ccd/templates/ingress.yaml
ccd/values.yaml
ci-values.yaml

https://tools.hmcts.net/jira/browse/RPE-871
Make case management web and api gateway optional, combined as one flag as no reason to have api gateway if you don't have case management web
Changed dns name to be based on ingress host not service name
```
[ ] Yes
[ ] No
```

RPE-871 Add flag to the UI and fix dns address

---

README.md
ccd/Chart.yaml

https://tools.hmcts.net/jira/browse/RPE-871
Add all docs, prepare for initial release
1.0.0 will be after this is used in a real application and importing spreadsheets automatically is done
```
[ ] Yes
[ ] No
```

RPE-871 Update documentation

---

README.md

https://tools.hmcts.net/jira/browse/RPE-884
Give example on how to retrieve secrets from multiple vaults
```
[ ] Yes
[ ] No
```

RPE-884 Update secrets docs

---

ccd/Chart.yaml
ccd/templates/data-store-api.yaml

Add ccd_dm_domain env var with default value to data-store
```
[ ] Yes
[x] No
```

Add dm_domain env var with default

---

ccd/Chart.yaml
ccd/templates/_helpers.tpl
ccd/templates/definition-importer.yaml

Read github credentials from vault to access definitions files from private repos.
```
[ ] Yes
[x] No
```

 Read github credentials from vault

---

ccd/Chart.yaml
ccd/templates/data-store-api.yaml
ccd/values.yaml

Add draft store url
```
[ ] Yes
[x] No
```

Add draft store support

---

README.md
ccd/Chart.yaml
ccd/templates/print-api-service.yaml
ccd/templates/print-api.yaml
ccd/values.yaml

Add ccd case print service
```
[ ] Yes
[x] No
```

Add ccd case print service

---

ccd/Chart.yaml
ccd/templates/dns.yaml
ccd/templates/ingress.yaml

Add ingress
```
[ ] Yes
[ ] No
```

RPE-910 Add ingress for print service

---

ccd/values.yaml

should help achieve higher pod density on the nodes

reduce CPU requests

---

README.md

Add docs on accessing case management web
```
[ ] Yes
[ ] No
```

Add docs on ingress to containers

---

ccd/Chart.yaml
ccd/templates/definition-importer.yaml
ccd/values.yaml

Configurable secret ref

---

README.md

Update README: include admin-web in stack description
```
[ ] Yes
[ x ] No
```

Update README to include adminWeb

---

ccd/Chart.yaml
ci-values.yaml

Pipeline failing and its hard to explain...increasing timeout for ci pipeline. Bit of a hopeful exeriment tbh.
```
[ ] Yes
[x] No
```

Increase delays to 120s

---

ccd/Chart.yaml
ccd/requirements.yaml
ccd/values.yaml

Add tagging for Postres. Services can then make optional and use only one Postgres instance, setting up locally.
```
[ ] Yes
[x] No
```

Tag Postgres dependency

---

README.md

Extra line break in README configuration section. 
```
[ ] Yes
[x] No
```

Fix rendering of configuration in README

---

ccd/Chart.yaml
ccd/templates/admin-web.yaml
ccd/values.yaml

Two minor changes:
- SIDAM as default
- Web Admin missing env vars (saves defining in environment block)
```
[ ] Yes
[x] No
```

Minor tweaks: from using in PR environment

---

README.md

Minor updates to README
```
[ ] Yes
[x] No
```

Some minor readme updates from working AKS deployment

---

ccd/Chart.yaml
ccd/requirements.yaml

Some changes in 2.1.0 that should help with HMCTS Demo - flux upgrades getting stuck because job already exists.
```
[ ] Yes
[x] No
```

Bump IDAM PR chart

---

ccd/Chart.yaml

Bump chart version so all minor releases of dependencies (e.g. IDAM PR chart) are updated.
```
[ ] Yes
[x] No
```

Update helm dependencies

---

ccd/Chart.yaml
ccd/requirements.yaml

add hmctspublic
```
[ ] Yes
[ x] No
```

add hmctspublic

---

ccd/Chart.yaml
ccd/requirements.yaml
ccd/values.yaml

bump version
```
[ ] Yes
[ x] No
```

bump version

---

Makefile
README.md

update Makefile to make testing on new Sandbox easier
```
[ ] Yes
[x ] No
```

update Makefile to use new AKS sandbox

---

README.md

N/A
Updated idamClientSecret example value in README
```
[ ] Yes
[x] No
```

Updated idamClientSecret example value in README

---

ccd/requirements.yaml
ccd/values-sandbox.yaml
ccd/values.yaml
ci-values.yaml

RDM-5309-refactored

---

ccd/Chart.yaml
ccd/requirements.yaml
ccd/values-sandbox.yaml
ccd/values.yaml
ci-values.yaml

Various improvements

---

README.md
azure-pipelines.yml
ccd/Chart.yaml
ccd/requirements.yaml
ccd/values-sandbox.yaml
ccd/values.yaml
ci-values.yaml

improvements to chart-ccd part 2 [WIP]

---

ccd/Chart.yaml
ccd/requirements.yaml
ccd/values.yaml

Bumping to latest api gateway to make ingress class configurable
```
[ ] Yes
[x] No
```

Bump api gateway

---

ccd/Chart.yaml
ccd/values.yaml

fix wrong idam-pr adming web url

---

k8s/bin/vault-to-sealedsecret.sh

added sealed secret script

---

ccd/values.yaml

RDM-6193-moved more attribs from flux config

---

README.md
ccd/Chart.yaml
ccd/values.yaml

RDM-6193-PG-Persis

---

ccd/requirements.yaml
ccd/values.yaml
ci-values.yaml

RDM-6151-Added Definition Importer

---

ccd/values.yaml

RDM-6193- move attribs from flux

---

.gitignore
Makefile
ccd/requirements.yaml
ccd/values.yaml
ci-values.yaml

RDM-6151- modified definiton importer chart version

---

ccd/requirements.yaml
ccd/values.yaml

Adding templating to chart

---

ccd/Chart.yaml

RDM-6151- chart release version bumped up

---

azure-pipelines.yml
ccd/Chart.yaml

Chart CCD being released on 2.14.3

---

ccd/Chart.yaml
ccd/values.yaml

Tested on preview:
ccd-test-ccd-admin-web-76db66fdd4-xmlqt          1/1     Running     0          21m
ccd-test-ccd-data-store-api-5cb97f8dc5-jgtf8     1/1     Running     1          21m
ccd-test-ccd-definition-store-887d9fcc7-vk98x    1/1     Running     0          21m
ccd-test-ccd-user-profile-api-844794f6dd-4m2kr   1/1     Running     0          21m
ccd-test-definition-importer-xh8lr               0/1     Completed   0          16m
ccd-test-postgresql-0                            1/1     Running     0          21m
ccd-test-s2s-674db68465-4ljz9                    1/1     Running     0          21m
ccd-test-user-profile-importer-lbctc             0/1     Completed   0          16m
```
[ ] Yes
[x] No
```

RDM-6626-Service-Defaults

---

ccd/values.yaml

Added memory on definition store api
```
[ ] Yes
[ ] No
```

upgraded mem limits on definition-store

---

ccd/Chart.yaml
ccd/values.yaml

Revert "upgraded mem limits on definition-store"

---

ccd/Chart.yaml
ccd/values.yaml

upgrade memory

---

ccd/Chart.yaml
ccd/values.yaml

Moved CORS_ORIGIN_WHITELIST from flux
```
[ ] Yes
[ x] No
```

RDM-6756-moved flux config

---

ccd/Chart.yaml
ccd/values.yaml

adding secrets

---

ccd/Chart.yaml

fix wrong version

---

azure-pipelines.yml
ccd/Chart.yaml
ccd/requirements.yaml

moving to helm 3

---

ccd/Chart.yaml
ccd/requirements.yaml

Bumping definition importer chart

---

ccd/Chart.yaml
ccd/templates/admin-web.yaml
ccd/templates/api-gateway.yaml
ccd/templates/case-management-web.yaml
ccd/templates/data-store-api.yaml
ccd/templates/definition-importer.yaml
ccd/templates/definition-store-api.yaml
ccd/templates/print-api.yaml
ccd/templates/user-profile-api.yaml
ccd/templates/user-profile-importer.yaml
ccd/values.yaml

Makes imagePullPolicy configurable so when product is installed it can always pull latest images. 
```
[ ] Yes
[X] No
```

impr: image pull policy is now configurable

---

azure-pipelines.yml

Use proper names for test charts
```
[ ] Yes
[X] No
```

fix: use proper names for 3.x branch

---

README.md
ccd/Chart.yaml
ccd/requirements.yaml
ccd/templates/definition-importer.yaml
ccd/templates/dns.yaml
ccd/templates/user-profile-importer.yaml
ccd/values.yaml

Clean up resources after completion (1 hr) of idam-pr.
```
[ ] Yes
[X] No
```

impr: clean up Job hooks

---

ccd/Chart.yaml
ccd/requirements.yaml

Update postgres chart version to match chart-java

---

ccd/Chart.yaml
ccd/requirements.yaml
ccd/values.yaml
ci-values.yaml

upgrade definition & user-profile importers
```
[ ] Yes
[ x] No
```

upgrade importers

---

ccd/Chart.yaml
ccd/templates/dns.yaml

As in title
```
[ ] Yes
[X] No
```

impr: remove post-upgrade for dns hook

---

ccd/Chart.yaml
ccd/requirements.yaml
ccd/values.yaml
ci-values.yaml

related to: https://github.com/hmcts/ccd-case-management-web/pull/943
hmcts/chart-idam-pr#22

Update ccd-case-management-web chart version

---

ccd/Chart.yaml
ccd/requirements.yaml

update ccd-web-admin & bump chart version
```
[ ] Yes
[x ] No
```

update some dependencies

---

ccd/requirements.yaml
ccd/values.yaml

Update Chart Versions

---

ccd/Chart.yaml
ccd/values.yaml

https://tools.hmcts.net/jira/browse/RDM-11956
Extend allowed list of document domains to include em-hrs-api
```
[ ] Yes
[X] No
```

RDM-11956 Extend allowed list of document domains to include em-hrs-api

---

ccd/Chart.yaml

https://tools.hmcts.net/jira/browse/RDM-12054
Upgrade Base Chart Versions (Java & Nodejs)
```
[ ] Yes
[X] No
```

RDM-12054 Upgrade Base Chart Versions (Java & Nodejs)

---

ccd/values.yaml
ci-values.yaml

Add in data store system user details

---

ccd/Chart.yaml

https://tools.hmcts.net/jira/browse/CCD-1711
```
[ ] Yes
[x] No
```

Update Chart.yaml bump all

---

README.md
ccd/Chart.yaml
ccd/values.yaml

Include Role Assignment Service

---

README.md
ccd/Chart.yaml
ccd/values.yaml

https://tools.hmcts.net/jira/browse/CCD-2418
```
[ ] Yes
[x] No
```

Remove ccpay

---

ccd/Chart.yaml

Upgrade to Latest Base Helm Charts

---

ccd/Chart.yaml
ccd/values.yaml
ci-values.yaml

https://tools.hmcts.net/jira/browse/CCD-3376
AKS is failing in Preview Env - update ccd charts
```
[ ] Yes
[x] No
```

Ccd 3376 master 4

---

ccd/Chart.yaml
ccd/values.yaml

https://tools.hmcts.net/jira/browse/CCD-3503
Chart-ccd Upgrade Java, postgresql and redis configurations
```
[ ] Yes
[x] No
```

Ccd 3434 master 2

---

README.md
ccd/Chart.yaml
ccd/values.yaml
ci-values.yaml

Ccd 2552 add message-publisher and bump

---

ccd/Chart.yaml

https://tools.hmcts.net/jira/browse/CCD-4317
Upgrade base charts
```
[ ] Yes
[X] No
```

CCD-4317 Update Chart.yaml

---

ccd/Chart.yaml

https://tools.hmcts.net/jira/browse/CCD-4396
New version of data-store with updated ES chart
```
[ ] Yes
[X] No
```

CCD-4396: Update Chart.yaml

---

ccd/Chart.yaml
ccd/values.yaml

Update  logstash 

---

ccd/Chart.yaml

https://tools.hmcts.net/jira/browse/CCD-4398
CCD-4398: Bump ccd charts
```
[ ] Yes
[X] No
```

CCD-4398: Bump ccd charts

---

README.md
ccd/Chart.yaml
ccd/values.yaml
ci-values.yaml

- [ X] commit messages are meaningful and follow good commit message guidelines
This change will allow to create the postgres databases with change_id prefix so it will be separate database per PR.
```
[ ] Yes
[ X ] No
```

Fix: added CHANGE_ID to create pr based databases

---

ccd/Chart.yaml

upgrade chart version for role assignment service

---

ccd/Chart.yaml

* New version of _am-role-assignment-service_ has been released
* This version updates its dependency on chart-java to 5.0.3 which fixes a bug encountered when user-defined affinity values are specified
```
[ ] Yes
[x] No
```

Upgrade am-role-assignment-service chart to 0.0.75

---

ccd/Chart.yaml

Update Chart.yaml for data-store

---

ccd/Chart.yaml

Similar pr was opened with failures due to ccd-admin-web and ccd-data-store-api not having passing builds since being bumped, retesting here with these set to latest existing versions

Chart upgrades
